version: '3'

services:
  db:
    image: mongo:5.0.14
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATABASE=pokedex
    volumes:
      - ./mongo:/data/db # here instead of a named volume we use a local folder to persist the data